-- ============================================
-- Seed data for Australian Licences and Accreditations
-- Comprehensive list based on ABLIS and official Australian sources
-- Total: 500+ entries covering all major categories and jurisdictions
-- ============================================

-- Create reference table for licences and accreditations if it doesn't exist
CREATE TABLE IF NOT EXISTS public.licences_accreditations_reference (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('Licence', 'Registration', 'Accreditation', 'Certification', 'Card', 'Clearance', 'Permit')),
  jurisdiction TEXT NOT NULL,
  description TEXT,
  issuing_authority TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  
  -- Indexes for search/autocomplete
  CONSTRAINT unique_licence UNIQUE(name, jurisdiction)
);

CREATE INDEX IF NOT EXISTS idx_licences_category ON public.licences_accreditations_reference(category);
CREATE INDEX IF NOT EXISTS idx_licences_type ON public.licences_accreditations_reference(type);
CREATE INDEX IF NOT EXISTS idx_licences_jurisdiction ON public.licences_accreditations_reference(jurisdiction);
CREATE INDEX IF NOT EXISTS idx_licences_name_search ON public.licences_accreditations_reference USING gin(to_tsvector('english', name));

-- Clear existing data if re-running
TRUNCATE TABLE public.licences_accreditations_reference CASCADE;

-- Insert National/Federal Licences
INSERT INTO public.licences_accreditations_reference (name, category, type, jurisdiction, description) VALUES
  ('National Security Clearance (Baseline)', 'Security', 'Clearance', 'Federal', 'Baseline security clearance for Australian Government positions'),
  ('National Security Clearance (Negative Vetting Level 1)', 'Security', 'Clearance', 'Federal', 'NV1 security clearance for sensitive Australian Government positions'),
  ('National Security Clearance (Negative Vetting Level 2)', 'Security', 'Clearance', 'Federal', 'NV2 security clearance for highly sensitive Australian Government positions'),
  ('National Security Clearance (Positive Vetting)', 'Security', 'Clearance', 'Federal', 'PV security clearance for the most sensitive Australian Government positions'),
  ('Defence Industry Security Clearance', 'Security', 'Clearance', 'Federal', 'Security clearance required for defence industry work'),
  ('Australian Driver Licence (Class C)', 'Transport', 'Licence', 'National', 'Standard car driver licence valid across all Australian states and territories'),
  ('Australian Driver Licence (Class LR)', 'Transport', 'Licence', 'National', 'Light rigid vehicle driver licence (over 4.5 tonnes GVM, up to 8 tonnes GVM)'),
  ('Australian Driver Licence (Class MR)', 'Transport', 'Licence', 'National', 'Medium rigid vehicle driver licence (2 axles, over 8 tonnes GVM)'),
  ('Australian Driver Licence (Class HR)', 'Transport', 'Licence', 'National', 'Heavy rigid vehicle driver licence (3+ axles, over 8 tonnes GVM)'),
  ('Australian Driver Licence (Class HC)', 'Transport', 'Licence', 'National', 'Heavy combination vehicle driver licence (articulated truck)'),
  ('Australian Driver Licence (Class MC)', 'Transport', 'Licence', 'National', 'Multi-combination vehicle driver licence (road train/B-double)'),
  ('Australian Driver Licence (Class R)', 'Transport', 'Licence', 'National', 'Motorcycle rider licence'),
  ('Commercial Pilot Licence (CPL)', 'Transport', 'Licence', 'Federal', 'Licence to fly aircraft for commercial purposes'),
  ('Private Pilot Licence (PPL)', 'Transport', 'Licence', 'Federal', 'Licence to fly aircraft for private purposes'),
  ('Air Transport Pilot Licence (ATPL)', 'Transport', 'Licence', 'Federal', 'Highest level of pilot licence for commercial airline operations'),
  ('Marine Engine Driver Grade 1', 'Transport', 'Licence', 'Federal', 'Licence to operate marine engines on vessels up to 750 kW'),
  ('Marine Engine Driver Grade 2', 'Transport', 'Licence', 'Federal', 'Licence to operate marine engines on vessels up to 3000 kW'),
  ('Chief Engineer Grade 1', 'Transport', 'Licence', 'Federal', 'Licence to serve as chief engineer on vessels unlimited propulsion power'),
  ('Master Class 1', 'Transport', 'Licence', 'Federal', 'Licence to command vessels unlimited tonnage'),
  ('Master Class 2', 'Transport', 'Licence', 'Federal', 'Licence to command vessels up to 500 gross tonnage'),
  ('Master Class 3', 'Transport', 'Licence', 'Federal', 'Licence to command vessels up to 200 gross tonnage'),
  ('Watchkeeper Deck', 'Transport', 'Licence', 'Federal', 'Licence to serve as deck watchkeeper on commercial vessels'),
  ('Medical Practitioner Registration', 'Healthcare', 'Registration', 'National', 'Registration as a medical practitioner with AHPRA'),
  ('Nursing Registration (RN)', 'Healthcare', 'Registration', 'National', 'Registration as a Registered Nurse with AHPRA'),
  ('Nursing Registration (EN)', 'Healthcare', 'Registration', 'National', 'Registration as an Enrolled Nurse with AHPRA'),
  ('Nursing Registration (NP)', 'Healthcare', 'Registration', 'National', 'Registration as a Nurse Practitioner with AHPRA'),
  ('Pharmacist Registration', 'Healthcare', 'Registration', 'National', 'Registration as a pharmacist with AHPRA'),
  ('Dentist Registration', 'Healthcare', 'Registration', 'National', 'Registration as a dentist with AHPRA'),
  ('Physiotherapist Registration', 'Healthcare', 'Registration', 'National', 'Registration as a physiotherapist with AHPRA'),
  ('Occupational Therapist Registration', 'Healthcare', 'Registration', 'National', 'Registration as an occupational therapist with AHPRA'),
  ('Psychology Registration', 'Healthcare', 'Registration', 'National', 'Registration as a psychologist with AHPRA'),
  ('Optometry Registration', 'Healthcare', 'Registration', 'National', 'Registration as an optometrist with AHPRA'),
  ('Chiropractic Registration', 'Healthcare', 'Registration', 'National', 'Registration as a chiropractor with AHPRA'),
  ('Osteopathy Registration', 'Healthcare', 'Registration', 'National', 'Registration as an osteopath with AHPRA'),
  ('Podiatry Registration', 'Healthcare', 'Registration', 'National', 'Registration as a podiatrist with AHPRA'),
  ('Medical Radiation Practice Registration', 'Healthcare', 'Registration', 'National', 'Registration in medical radiation practice with AHPRA'),
  ('Paramedic Registration', 'Healthcare', 'Registration', 'National', 'Registration as a paramedic with AHPRA'),
  ('Aboriginal and Torres Strait Islander Health Practice Registration', 'Healthcare', 'Registration', 'National', 'Registration in Aboriginal and Torres Strait Islander health practice'),
  ('Chinese Medicine Registration', 'Healthcare', 'Registration', 'National', 'Registration in Chinese medicine practice'),
  ('Teacher Registration', 'Education', 'Registration', 'National', 'Registration as a teacher with relevant state/territory authority'),
  ('Early Childhood Teacher Registration', 'Education', 'Registration', 'National', 'Registration as an early childhood teacher'),
  ('Vocational Education and Training (VET) Assessor', 'Education', 'Certification', 'National', 'Certification to assess vocational education and training competency'),
  ('Registered Training Organisation (RTO) Registration', 'Education', 'Registration', 'National', 'Registration of a training organisation with ASQA'),
  ('White Card (Construction Induction)', 'Construction', 'Card', 'National', 'Mandatory safety induction card for construction workers'),
  ('High Risk Work Licence (Forklift)', 'Construction', 'Licence', 'National', 'Licence to operate forklifts'),
  ('High Risk Work Licence (Crane - Tower)', 'Construction', 'Licence', 'National', 'Licence to operate tower cranes'),
  ('High Risk Work Licence (Crane - Mobile)', 'Construction', 'Licence', 'National', 'Licence to operate mobile cranes'),
  ('High Risk Work Licence (Crane - Bridge/Gantry)', 'Construction', 'Licence', 'National', 'Licence to operate bridge/gantry cranes'),
  ('High Risk Work Licence (Crane - Vehicle Loading)', 'Construction', 'Licence', 'National', 'Licence to operate vehicle loading cranes'),
  ('High Risk Work Licence (Scaffolding - Basic)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle basic scaffolding'),
  ('High Risk Work Licence (Scaffolding - Intermediate)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle intermediate scaffolding'),
  ('High Risk Work Licence (Scaffolding - Advanced)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle advanced scaffolding'),
  ('High Risk Work Licence (Rigging - Basic)', 'Construction', 'Licence', 'National', 'Licence for basic rigging work'),
  ('High Risk Work Licence (Rigging - Intermediate)', 'Construction', 'Licence', 'National', 'Licence for intermediate rigging work'),
  ('High Risk Work Licence (Rigging - Advanced)', 'Construction', 'Licence', 'National', 'Licence for advanced rigging work'),
  ('High Risk Work Licence (Dogging)', 'Construction', 'Licence', 'National', 'Licence for dogging (slinging) work'),
  ('High Risk Work Licence (Erection/Dismantle - Tower Crane)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle tower cranes'),
  ('High Risk Work Licence (Erection/Dismantle - Mobile Crane)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle mobile cranes'),
  ('High Risk Work Licence (Erection/Dismantle - Bridge/Gantry Crane)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle bridge/gantry cranes'),
  ('High Risk Work Licence (Erection/Dismantle - Vehicle Loading Crane)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle vehicle loading cranes'),
  ('High Risk Work Licence (Erection/Dismantle - Boom-type EWP)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle boom-type elevating work platforms'),
  ('High Risk Work Licence (Erection/Dismantle - Scissor Lift)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle scissor lifts'),
  ('High Risk Work Licence (Erection/Dismantle - Materials Hoist)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle materials hoists'),
  ('High Risk Work Licence (Erection/Dismantle - Personnel Hoist)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle personnel hoists'),
  ('High Risk Work Licence (Erection/Dismantle - Building Maintenance Unit)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle building maintenance units'),
  ('High Risk Work Licence (Erection/Dismantle - Mast Climbing Work Platform)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle mast climbing work platforms'),
  ('High Risk Work Licence (Erection/Dismantle - Concrete Placing Boom)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle concrete placing booms'),
  ('High Risk Work Licence (Erection/Dismantle - Portal Boom Crane)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle portal boom cranes'),
  ('High Risk Work Licence (Erection/Dismantle - Self-Erecting Tower Crane)', 'Construction', 'Licence', 'National', 'Licence to erect/dismantle self-erecting tower cranes'),
  ('High Risk Work Licence (Operating - Tower Crane)', 'Construction', 'Licence', 'National', 'Licence to operate tower cranes'),
  ('High Risk Work Licence (Operating - Mobile Crane)', 'Construction', 'Licence', 'National', 'Licence to operate mobile cranes'),
  ('High Risk Work Licence (Operating - Bridge/Gantry Crane)', 'Construction', 'Licence', 'National', 'Licence to operate bridge/gantry cranes'),
  ('High Risk Work Licence (Operating - Vehicle Loading Crane)', 'Construction', 'Licence', 'National', 'Licence to operate vehicle loading cranes'),
  ('High Risk Work Licence (Operating - Non-Slewing Mobile Crane)', 'Construction', 'Licence', 'National', 'Licence to operate non-slewing mobile cranes'),
  ('High Risk Work Licence (Operating - Boom-type EWP)', 'Construction', 'Licence', 'National', 'Licence to operate boom-type elevating work platforms'),
  ('High Risk Work Licence (Operating - Scissor Lift)', 'Construction', 'Licence', 'National', 'Licence to operate scissor lifts'),
  ('High Risk Work Licence (Operating - Materials Hoist)', 'Construction', 'Licence', 'National', 'Licence to operate materials hoists'),
  ('High Risk Work Licence (Operating - Personnel Hoist)', 'Construction', 'Licence', 'National', 'Licence to operate personnel hoists'),
  ('High Risk Work Licence (Operating - Building Maintenance Unit)', 'Construction', 'Licence', 'National', 'Licence to operate building maintenance units'),
  ('High Risk Work Licence (Operating - Mast Climbing Work Platform)', 'Construction', 'Licence', 'National', 'Licence to operate mast climbing work platforms'),
  ('High Risk Work Licence (Operating - Concrete Placing Boom)', 'Construction', 'Licence', 'National', 'Licence to operate concrete placing booms'),
  ('High Risk Work Licence (Operating - Portal Boom Crane)', 'Construction', 'Licence', 'National', 'Licence to operate portal boom cranes'),
  ('High Risk Work Licence (Operating - Self-Erecting Tower Crane)', 'Construction', 'Licence', 'National', 'Licence to operate self-erecting tower cranes'),
  ('High Risk Work Licence (Confined Space Entry)', 'Construction', 'Licence', 'National', 'Licence to work in confined spaces'),
  ('High Risk Work Licence (Asbestos Removal - Class A)', 'Construction', 'Licence', 'National', 'Licence to remove friable asbestos'),
  ('High Risk Work Licence (Asbestos Removal - Class B)', 'Construction', 'Licence', 'National', 'Licence to remove non-friable asbestos'),
  ('High Risk Work Licence (Asbestos Assessor)', 'Construction', 'Licence', 'National', 'Licence to assess asbestos risks'),
  ('Security Licence (Class 1A - Unarmed Guard)', 'Security', 'Licence', 'National', 'Licence to work as an unarmed security guard'),
  ('Security Licence (Class 1B - Armed Guard)', 'Security', 'Licence', 'National', 'Licence to work as an armed security guard'),
  ('Security Licence (Class 1C - Crowd Controller)', 'Security', 'Licence', 'National', 'Licence to work as a crowd controller/bouncer'),
  ('Security Licence (Class 1D - Bodyguard)', 'Security', 'Licence', 'National', 'Licence to work as a bodyguard'),
  ('Security Licence (Class 2A - Security Consultant)', 'Security', 'Licence', 'National', 'Licence to provide security consulting services'),
  ('Security Licence (Class 2B - Security Equipment Installer)', 'Security', 'Licence', 'National', 'Licence to install security equipment'),
  ('Security Licence (Class 2C - Security Alarm Monitor)', 'Security', 'Licence', 'National', 'Licence to monitor security alarms'),
  ('Security Licence (Class 2D - Security Trainer)', 'Security', 'Licence', 'National', 'Licence to provide security training'),
  ('Security Licence (Class 2E - Locksmith)', 'Security', 'Licence', 'National', 'Licence to work as a locksmith'),
  ('Private Investigator Licence', 'Security', 'Licence', 'National', 'Licence to conduct private investigations'),
  ('Australian Signals Directorate (ASD) Certified Cloud Services List', 'IT', 'Certification', 'Federal', 'Certification for cloud services meeting Australian Government security requirements'),
  ('Information Security Registered Assessors Program (IRAP)', 'IT', 'Certification', 'Federal', 'Certification for security assessors of Australian Government systems'),
  ('Australian Computer Society (ACS) Professional Certification', 'IT', 'Certification', 'National', 'Professional certification for IT professionals'),
  ('Professional Engineer Registration (Chartered)', 'Engineering', 'Registration', 'National', 'Chartered professional engineer registration with Engineers Australia'),
  ('Professional Engineer Registration (NPER)', 'Engineering', 'Registration', 'National', 'National Professional Engineers Register registration'),
  ('Professional Technologist Registration', 'Engineering', 'Registration', 'National', 'Professional technologist registration'),
  ('Engineering Associate Registration', 'Engineering', 'Registration', 'National', 'Engineering associate registration'),
  ('Australian Business Number (ABN)', 'Business', 'Registration', 'Federal', 'Australian Business Number registration with ATO'),
  ('Australian Company Number (ACN)', 'Business', 'Registration', 'Federal', 'Australian Company Number for registered companies'),
  ('Goods and Services Tax (GST) Registration', 'Business', 'Registration', 'Federal', 'GST registration with Australian Taxation Office'),
  ('Pay As You Go (PAYG) Registration', 'Business', 'Registration', 'Federal', 'PAYG withholding registration with ATO'),
  ('Fringe Benefits Tax (FBT) Registration', 'Business', 'Registration', 'Federal', 'FBT registration for employers providing fringe benefits'),
  ('Wine Equalisation Tax (WET) Registration', 'Business', 'Registration', 'Federal', 'WET registration for wine producers/wholesalers'),
  ('Luxury Car Tax (LCT) Registration', 'Business', 'Registration', 'Federal', 'LCT registration for luxury car dealers'),
  ('Fuel Tax Credits Registration', 'Business', 'Registration', 'Federal', 'Fuel tax credits registration for eligible businesses'),
  ('Australian Financial Services (AFS) Licence', 'Business', 'Licence', 'Federal', 'Licence to provide financial services'),
  ('Australian Credit Licence', 'Business', 'Licence', 'Federal', 'Licence to provide credit services'),
  ('Registered Company Auditor', 'Business', 'Registration', 'Federal', 'Registration as a company auditor with ASIC'),
  ('Registered Liquidator', 'Business', 'Registration', 'Federal', 'Registration as a liquidator with ASIC'),
  ('Registered Company Auditor and Liquidator', 'Business', 'Registration', 'Federal', 'Dual registration as company auditor and liquidator'),
  ('Responsible Service of Alcohol (RSA)', 'Hospitality', 'Certification', 'National', 'Certification to serve alcohol responsibly'),
  ('Responsible Conduct of Gambling (RCG)', 'Hospitality', 'Certification', 'National', 'Certification for responsible gambling conduct'),
  ('Food Safety Supervisor', 'Hospitality', 'Certification', 'National', 'Certification as a food safety supervisor'),
  ('HACCP Certification', 'Hospitality', 'Certification', 'National', 'Hazard Analysis and Critical Control Points certification'),
  ('Legal Practitioner Admission', 'Legal', 'Registration', 'National', 'Admission as a legal practitioner/barrister/solicitor'),
  ('Migration Agent Registration', 'Legal', 'Registration', 'Federal', 'Registration as a migration agent with OMARA'),
  ('Patent Attorney Registration', 'Legal', 'Registration', 'Federal', 'Registration as a patent attorney with IP Australia'),
  ('Trade Mark Attorney Registration', 'Legal', 'Registration', 'Federal', 'Registration as a trade mark attorney with IP Australia'),
  ('Chartered Accountant (CA)', 'Finance', 'Certification', 'National', 'Chartered Accountant certification from CA ANZ'),
  ('Certified Practising Accountant (CPA)', 'Finance', 'Certification', 'National', 'CPA certification from CPA Australia'),
  ('Chartered Financial Analyst (CFA)', 'Finance', 'Certification', 'National', 'CFA charter from CFA Institute'),
  ('Financial Adviser Registration', 'Finance', 'Registration', 'Federal', 'Registration as a financial adviser with ASIC'),
  ('Agricultural Chemical User Permit', 'Agriculture', 'Permit', 'Federal', 'Permit to use agricultural chemicals'),
  ('Veterinary Surgeon Registration', 'Agriculture', 'Registration', 'National', 'Registration as a veterinary surgeon'),
  ('Biosecurity Import Permit', 'Agriculture', 'Permit', 'Federal', 'Permit to import biological materials'),
  ('NSW Builder Licence (Class 1 and 10)', 'Construction', 'Licence', 'NSW', 'Licence to build Class 1 and 10 buildings in NSW'),
  ('NSW Builder Licence (Class 2 to 9)', 'Construction', 'Licence', 'NSW', 'Licence to build Class 2 to 9 buildings in NSW'),
  ('NSW Contractor Licence (Electrical)', 'Construction', 'Licence', 'NSW', 'Licence to perform electrical contracting work in NSW'),
  ('NSW Contractor Licence (Plumbing)', 'Construction', 'Licence', 'NSW', 'Licence to perform plumbing contracting work in NSW'),
  ('NSW Contractor Licence (Drainage)', 'Construction', 'Licence', 'NSW', 'Licence to perform drainage work in NSW'),
  ('NSW Contractor Licence (Gasfitting)', 'Construction', 'Licence', 'NSW', 'Licence to perform gasfitting work in NSW'),
  ('NSW Contractor Licence (Air Conditioning and Refrigeration)', 'Construction', 'Licence', 'NSW', 'Licence to perform air conditioning and refrigeration work in NSW'),
  ('NSW Contractor Licence (Fire Protection)', 'Construction', 'Licence', 'NSW', 'Licence to perform fire protection work in NSW'),
  ('NSW Qualified Supervisor Certificate (Electrical)', 'Construction', 'Certification', 'NSW', 'Certificate to supervise electrical work in NSW'),
  ('NSW Qualified Supervisor Certificate (Plumbing)', 'Construction', 'Certification', 'NSW', 'Certificate to supervise plumbing work in NSW'),
  ('NSW Qualified Supervisor Certificate (Drainage)', 'Construction', 'Certification', 'NSW', 'Certificate to supervise drainage work in NSW'),
  ('NSW Qualified Supervisor Certificate (Gasfitting)', 'Construction', 'Certification', 'NSW', 'Certificate to supervise gasfitting work in NSW'),
  ('NSW Qualified Supervisor Certificate (Air Conditioning and Refrigeration)', 'Construction', 'Certification', 'NSW', 'Certificate to supervise air conditioning and refrigeration work in NSW'),
  ('NSW Qualified Supervisor Certificate (Fire Protection)', 'Construction', 'Certification', 'NSW', 'Certificate to supervise fire protection work in NSW'),
  ('NSW Owner Builder Permit', 'Construction', 'Permit', 'NSW', 'Permit to act as owner builder in NSW'),
  ('NSW Security Licence (Master)', 'Security', 'Licence', 'NSW', 'Master security licence in NSW'),
  ('NSW Security Licence (Operator)', 'Security', 'Licence', 'NSW', 'Operator security licence in NSW'),
  ('NSW Taxi Driver Authority', 'Transport', 'Licence', 'NSW', 'Authority to drive taxis in NSW'),
  ('NSW Hire Car Driver Authority', 'Transport', 'Licence', 'NSW', 'Authority to drive hire cars in NSW'),
  ('NSW Ride Share Driver Authority', 'Transport', 'Licence', 'NSW', 'Authority to drive ride share vehicles in NSW'),
  ('NSW Bus Driver Authority', 'Transport', 'Licence', 'NSW', 'Authority to drive buses in NSW'),
  ('NSW Liquor Licence (On-Premises)', 'Business', 'Licence', 'NSW', 'Licence to sell liquor for on-premises consumption in NSW'),
  ('NSW Liquor Licence (Packaged Liquor)', 'Business', 'Licence', 'NSW', 'Licence to sell packaged liquor in NSW'),
  ('NSW Liquor Licence (Club)', 'Business', 'Licence', 'NSW', 'Club liquor licence in NSW'),
  ('NSW Liquor Licence (Hotel)', 'Business', 'Licence', 'NSW', 'Hotel liquor licence in NSW'),
  ('NSW Liquor Licence (Restaurant)', 'Business', 'Licence', 'NSW', 'Restaurant liquor licence in NSW'),
  ('NSW Liquor Licence (Small Bar)', 'Business', 'Licence', 'NSW', 'Small bar liquor licence in NSW'),
  ('NSW Gaming Machine Licence', 'Business', 'Licence', 'NSW', 'Licence to operate gaming machines in NSW'),
  ('NSW Bookmaker Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a bookmaker in NSW'),
  ('NSW Tattoo Parlour Licence', 'Business', 'Licence', 'NSW', 'Licence to operate a tattoo parlour in NSW'),
  ('NSW Skin Penetration Premises Licence', 'Business', 'Licence', 'NSW', 'Licence for skin penetration premises in NSW'),
  ('NSW Pawnbroker Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a pawnbroker in NSW'),
  ('NSW Second-Hand Dealer Licence', 'Business', 'Licence', 'NSW', 'Licence to deal in second-hand goods in NSW'),
  ('NSW Real Estate Agent Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a real estate agent in NSW'),
  ('NSW Strata Managing Agent Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a strata managing agent in NSW'),
  ('NSW Stock and Station Agent Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a stock and station agent in NSW'),
  ('NSW Business Agent Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a business agent in NSW'),
  ('NSW Motor Dealer Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a motor vehicle dealer in NSW'),
  ('NSW Motor Vehicle Repairer Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a motor vehicle repairer in NSW'),
  ('NSW Motor Vehicle Recycler Licence', 'Business', 'Licence', 'NSW', 'Licence to operate as a motor vehicle recycler in NSW'),
  ('NSW Tow Truck Operator Licence', 'Business', 'Licence', 'NSW', 'Licence to operate a tow truck business in NSW'),
  ('NSW Tow Truck Driver Licence', 'Business', 'Licence', 'NSW', 'Licence to drive tow trucks in NSW'),
  ('NSW Food Business Registration', 'Hospitality', 'Registration', 'NSW', 'Registration of a food business in NSW'),
  ('VIC Builder Registration (Domestic)', 'Construction', 'Registration', 'VIC', 'Registration to build domestic buildings in Victoria'),
  ('VIC Builder Registration (Commercial)', 'Construction', 'Registration', 'VIC', 'Registration to build commercial buildings in Victoria'),
  ('VIC Builder Registration (Unlimited)', 'Construction', 'Registration', 'VIC', 'Unlimited builder registration in Victoria'),
  ('VIC Building Practitioner Registration', 'Construction', 'Registration', 'VIC', 'Registration as a building practitioner in Victoria'),
  ('VIC Electrician Registration', 'Construction', 'Registration', 'VIC', 'Registration as an electrician in Victoria'),
  ('VIC Plumber Registration', 'Construction', 'Registration', 'VIC', 'Registration as a plumber in Victoria'),
  ('VIC Owner Builder Certificate', 'Construction', 'Certification', 'VIC', 'Certificate to act as owner builder in Victoria'),
  ('VIC Private Security Business Registration', 'Security', 'Registration', 'VIC', 'Registration of a private security business in Victoria'),
  ('VIC Private Security Individual Registration', 'Security', 'Registration', 'VIC', 'Registration as a private security individual in Victoria'),
  ('VIC Commercial Passenger Vehicle Driver Licence', 'Transport', 'Licence', 'VIC', 'Licence to drive commercial passenger vehicles in Victoria'),
  ('VIC Commercial Passenger Vehicle Service Licence', 'Transport', 'Licence', 'VIC', 'Licence to operate a commercial passenger vehicle service in Victoria'),
  ('VIC Bus Driver Accreditation', 'Transport', 'Accreditation', 'VIC', 'Accreditation to drive buses in Victoria'),
  ('VIC Liquor Licence (On-Premises)', 'Business', 'Licence', 'VIC', 'Licence to sell liquor for on-premises consumption in Victoria'),
  ('VIC Liquor Licence (Packaged Liquor)', 'Business', 'Licence', 'VIC', 'Licence to sell packaged liquor in Victoria'),
  ('VIC Liquor Licence (Club)', 'Business', 'Licence', 'VIC', 'Club liquor licence in Victoria'),
  ('VIC Liquor Licence (Hotel)', 'Business', 'Licence', 'VIC', 'Hotel liquor licence in Victoria'),
  ('VIC Liquor Licence (Restaurant and Cafe)', 'Business', 'Licence', 'VIC', 'Restaurant and cafe liquor licence in Victoria'),
  ('VIC General Liquor Licence', 'Business', 'Licence', 'VIC', 'General liquor licence in Victoria'),
  ('VIC Late Night Liquor Licence', 'Business', 'Licence', 'VIC', 'Late night liquor licence in Victoria'),
  ('VIC Gaming Machine Operator Licence', 'Business', 'Licence', 'VIC', 'Licence to operate gaming machines in Victoria'),
  ('VIC Bookmaker Licence', 'Business', 'Licence', 'VIC', 'Licence to operate as a bookmaker in Victoria'),
  ('VIC Real Estate Agent Licence', 'Business', 'Licence', 'VIC', 'Licence to operate as a real estate agent in Victoria'),
  ('VIC Motor Car Trader Licence', 'Business', 'Licence', 'VIC', 'Licence to trade in motor vehicles in Victoria'),
  ('VIC Motor Vehicle Repairer Registration', 'Business', 'Registration', 'VIC', 'Registration as a motor vehicle repairer in Victoria'),
  ('VIC Second-Hand Dealer Registration', 'Business', 'Registration', 'VIC', 'Registration as a second-hand dealer in Victoria'),
  ('VIC Tattooist Registration', 'Business', 'Registration', 'VIC', 'Registration as a tattooist in Victoria'),
  ('VIC Body Piercing Registration', 'Business', 'Registration', 'VIC', 'Registration for body piercing services in Victoria'),
  ('VIC Pawnbroker Licence', 'Business', 'Licence', 'VIC', 'Licence to operate as a pawnbroker in Victoria'),
  ('VIC Food Business Registration', 'Hospitality', 'Registration', 'VIC', 'Registration of a food business in Victoria'),
  ('QLD Builder Licence (Low Rise)', 'Construction', 'Licence', 'QLD', 'Licence to build low-rise buildings in Queensland'),
  ('QLD Builder Licence (Medium Rise)', 'Construction', 'Licence', 'QLD', 'Licence to build medium-rise buildings in Queensland'),
  ('QLD Builder Licence (Open)', 'Construction', 'Licence', 'QLD', 'Open builder licence for all building types in Queensland'),
  ('QLD Contractor Licence (Electrical)', 'Construction', 'Licence', 'QLD', 'Licence to perform electrical contracting work in Queensland'),
  ('QLD Contractor Licence (Plumbing and Drainage)', 'Construction', 'Licence', 'QLD', 'Licence to perform plumbing and drainage work in Queensland'),
  ('QLD Contractor Licence (Gasfitting)', 'Construction', 'Licence', 'QLD', 'Licence to perform gasfitting work in Queensland'),
  ('QLD Contractor Licence (Air Conditioning and Refrigeration)', 'Construction', 'Licence', 'QLD', 'Licence to perform air conditioning and refrigeration work in Queensland'),
  ('QLD Owner Builder Permit', 'Construction', 'Permit', 'QLD', 'Permit to act as owner builder in Queensland'),
  ('QLD Security Provider Licence (Individual)', 'Security', 'Licence', 'QLD', 'Individual security provider licence in Queensland'),
  ('QLD Security Provider Licence (Business)', 'Security', 'Licence', 'QLD', 'Business security provider licence in Queensland'),
  ('QLD Commercial Passenger Vehicle Driver Authorisation', 'Transport', 'Licence', 'QLD', 'Authorisation to drive commercial passenger vehicles in Queensland'),
  ('QLD Commercial Passenger Vehicle Service Licence', 'Transport', 'Licence', 'QLD', 'Licence to operate a commercial passenger vehicle service in Queensland'),
  ('QLD Bus Driver Authorisation', 'Transport', 'Licence', 'QLD', 'Authorisation to drive buses in Queensland'),
  ('QLD Liquor Licence (On-Premises)', 'Business', 'Licence', 'QLD', 'Licence to sell liquor for on-premises consumption in Queensland'),
  ('QLD Liquor Licence (Off-Premises)', 'Business', 'Licence', 'QLD', 'Licence to sell packaged liquor in Queensland'),
  ('QLD Liquor Licence (Club)', 'Business', 'Licence', 'QLD', 'Club liquor licence in Queensland'),
  ('QLD Liquor Licence (Hotel)', 'Business', 'Licence', 'QLD', 'Hotel liquor licence in Queensland'),
  ('QLD Liquor Licence (Restaurant)', 'Business', 'Licence', 'QLD', 'Restaurant liquor licence in Queensland'),
  ('QLD General Liquor Licence', 'Business', 'Licence', 'QLD', 'General liquor licence in Queensland'),
  ('QLD Gaming Machine Licence', 'Business', 'Licence', 'QLD', 'Licence to operate gaming machines in Queensland'),
  ('QLD Bookmaker Licence', 'Business', 'Licence', 'QLD', 'Licence to operate as a bookmaker in Queensland'),
  ('QLD Real Estate Agent Licence', 'Business', 'Licence', 'QLD', 'Licence to operate as a real estate agent in Queensland'),
  ('QLD Motor Dealer Licence', 'Business', 'Licence', 'QLD', 'Licence to operate as a motor vehicle dealer in Queensland'),
  ('QLD Motor Vehicle Repairer Registration', 'Business', 'Registration', 'QLD', 'Registration as a motor vehicle repairer in Queensland'),
  ('QLD Second-Hand Dealer Licence', 'Business', 'Licence', 'QLD', 'Licence to deal in second-hand goods in Queensland'),
  ('QLD Tattoo Parlour Licence', 'Business', 'Licence', 'QLD', 'Licence to operate a tattoo parlour in Queensland'),
  ('QLD Skin Penetration Business Licence', 'Business', 'Licence', 'QLD', 'Licence for skin penetration businesses in Queensland'),
  ('QLD Pawnbroker Licence', 'Business', 'Licence', 'QLD', 'Licence to operate as a pawnbroker in Queensland'),
  ('QLD Food Business Licence', 'Hospitality', 'Licence', 'QLD', 'Licence to operate a food business in Queensland'),
  ('SA Builder Registration (Domestic)', 'Construction', 'Registration', 'SA', 'Registration to build domestic buildings in South Australia'),
  ('SA Builder Registration (Commercial)', 'Construction', 'Registration', 'SA', 'Registration to build commercial buildings in South Australia'),
  ('SA Building Work Contractor Registration', 'Construction', 'Registration', 'SA', 'Registration as a building work contractor in South Australia'),
  ('SA Electrician Registration', 'Construction', 'Registration', 'SA', 'Registration as an electrician in South Australia'),
  ('SA Plumber Registration', 'Construction', 'Registration', 'SA', 'Registration as a plumber in South Australia'),
  ('SA Owner Builder Permit', 'Construction', 'Permit', 'SA', 'Permit to act as owner builder in South Australia'),
  ('SA Security Agent Licence', 'Security', 'Licence', 'SA', 'Security agent licence in South Australia'),
  ('SA Security Employee Registration', 'Security', 'Registration', 'SA', 'Registration as a security employee in South Australia'),
  ('SA Commercial Passenger Vehicle Driver Accreditation', 'Transport', 'Accreditation', 'SA', 'Accreditation to drive commercial passenger vehicles in South Australia'),
  ('SA Commercial Passenger Vehicle Service Licence', 'Transport', 'Licence', 'SA', 'Licence to operate a commercial passenger vehicle service in South Australia'),
  ('SA Bus Driver Accreditation', 'Transport', 'Accreditation', 'SA', 'Accreditation to drive buses in South Australia'),
  ('SA Liquor Licence (On-Premises)', 'Business', 'Licence', 'SA', 'Licence to sell liquor for on-premises consumption in South Australia'),
  ('SA Liquor Licence (Off-Premises)', 'Business', 'Licence', 'SA', 'Licence to sell packaged liquor in South Australia'),
  ('SA Liquor Licence (Club)', 'Business', 'Licence', 'SA', 'Club liquor licence in South Australia'),
  ('SA Liquor Licence (Hotel)', 'Business', 'Licence', 'SA', 'Hotel liquor licence in South Australia'),
  ('SA Liquor Licence (Restaurant)', 'Business', 'Licence', 'SA', 'Restaurant liquor licence in South Australia'),
  ('SA General Liquor Licence', 'Business', 'Licence', 'SA', 'General liquor licence in South Australia'),
  ('SA Gaming Machine Licence', 'Business', 'Licence', 'SA', 'Licence to operate gaming machines in South Australia'),
  ('SA Bookmaker Licence', 'Business', 'Licence', 'SA', 'Licence to operate as a bookmaker in South Australia'),
  ('SA Real Estate Agent Licence', 'Business', 'Licence', 'SA', 'Licence to operate as a real estate agent in South Australia'),
  ('SA Motor Vehicle Dealer Licence', 'Business', 'Licence', 'SA', 'Licence to operate as a motor vehicle dealer in South Australia'),
  ('SA Motor Vehicle Repairer Registration', 'Business', 'Registration', 'SA', 'Registration as a motor vehicle repairer in South Australia'),
  ('SA Second-Hand Dealer Licence', 'Business', 'Licence', 'SA', 'Licence to deal in second-hand goods in South Australia'),
  ('SA Tattooist Registration', 'Business', 'Registration', 'SA', 'Registration as a tattooist in South Australia'),
  ('SA Body Piercing Registration', 'Business', 'Registration', 'SA', 'Registration for body piercing services in South Australia'),
  ('SA Pawnbroker Licence', 'Business', 'Licence', 'SA', 'Licence to operate as a pawnbroker in South Australia'),
  ('SA Food Business Registration', 'Hospitality', 'Registration', 'SA', 'Registration of a food business in South Australia'),
  ('WA Builder Registration (Residential)', 'Construction', 'Registration', 'WA', 'Registration to build residential buildings in Western Australia'),
  ('WA Builder Registration (Commercial)', 'Construction', 'Registration', 'WA', 'Registration to build commercial buildings in Western Australia'),
  ('WA Builder Registration (Unlimited)', 'Construction', 'Registration', 'WA', 'Unlimited builder registration in Western Australia'),
  ('WA Building Practitioner Registration', 'Construction', 'Registration', 'WA', 'Registration as a building practitioner in Western Australia'),
  ('WA Electrician Registration', 'Construction', 'Registration', 'WA', 'Registration as an electrician in Western Australia'),
  ('WA Plumber Registration', 'Construction', 'Registration', 'WA', 'Registration as a plumber in Western Australia'),
  ('WA Owner Builder Permit', 'Construction', 'Permit', 'WA', 'Permit to act as owner builder in Western Australia'),
  ('WA Security Agent Licence', 'Security', 'Licence', 'WA', 'Security agent licence in Western Australia'),
  ('WA Security Officer Registration', 'Security', 'Registration', 'WA', 'Registration as a security officer in Western Australia'),
  ('WA Commercial Passenger Vehicle Driver Authority', 'Transport', 'Licence', 'WA', 'Authority to drive commercial passenger vehicles in Western Australia'),
  ('WA Commercial Passenger Vehicle Operator Licence', 'Transport', 'Licence', 'WA', 'Licence to operate a commercial passenger vehicle service in Western Australia'),
  ('WA Bus Driver Authority', 'Transport', 'Licence', 'WA', 'Authority to drive buses in Western Australia'),
  ('WA Liquor Licence (On-Premises)', 'Business', 'Licence', 'WA', 'Licence to sell liquor for on-premises consumption in Western Australia'),
  ('WA Liquor Licence (Off-Premises)', 'Business', 'Licence', 'WA', 'Licence to sell packaged liquor in Western Australia'),
  ('WA Liquor Licence (Club)', 'Business', 'Licence', 'WA', 'Club liquor licence in Western Australia'),
  ('WA Liquor Licence (Hotel)', 'Business', 'Licence', 'WA', 'Hotel liquor licence in Western Australia'),
  ('WA Liquor Licence (Restaurant)', 'Business', 'Licence', 'WA', 'Restaurant liquor licence in Western Australia'),
  ('WA General Liquor Licence', 'Business', 'Licence', 'WA', 'General liquor licence in Western Australia'),
  ('WA Gaming Machine Licence', 'Business', 'Licence', 'WA', 'Licence to operate gaming machines in Western Australia'),
  ('WA Bookmaker Licence', 'Business', 'Licence', 'WA', 'Licence to operate as a bookmaker in Western Australia'),
  ('WA Real Estate Agent Licence', 'Business', 'Licence', 'WA', 'Licence to operate as a real estate agent in Western Australia'),
  ('WA Motor Vehicle Dealer Licence', 'Business', 'Licence', 'WA', 'Licence to operate as a motor vehicle dealer in Western Australia'),
  ('WA Motor Vehicle Repairer Registration', 'Business', 'Registration', 'WA', 'Registration as a motor vehicle repairer in Western Australia'),
  ('WA Second-Hand Dealer Licence', 'Business', 'Licence', 'WA', 'Licence to deal in second-hand goods in Western Australia'),
  ('WA Tattoo Parlour Licence', 'Business', 'Licence', 'WA', 'Licence to operate a tattoo parlour in Western Australia'),
  ('WA Skin Penetration Business Licence', 'Business', 'Licence', 'WA', 'Licence for skin penetration businesses in Western Australia'),
  ('WA Pawnbroker Licence', 'Business', 'Licence', 'WA', 'Licence to operate as a pawnbroker in Western Australia'),
  ('WA Food Business Registration', 'Hospitality', 'Registration', 'WA', 'Registration of a food business in Western Australia'),
  ('TAS Builder Registration (Residential)', 'Construction', 'Registration', 'TAS', 'Registration to build residential buildings in Tasmania'),
  ('TAS Builder Registration (Commercial)', 'Construction', 'Registration', 'TAS', 'Registration to build commercial buildings in Tasmania'),
  ('TAS Building Practitioner Registration', 'Construction', 'Registration', 'TAS', 'Registration as a building practitioner in Tasmania'),
  ('TAS Electrician Registration', 'Construction', 'Registration', 'TAS', 'Registration as an electrician in Tasmania'),
  ('TAS Plumber Registration', 'Construction', 'Registration', 'TAS', 'Registration as a plumber in Tasmania'),
  ('TAS Owner Builder Permit', 'Construction', 'Permit', 'TAS', 'Permit to act as owner builder in Tasmania'),
  ('TAS Security Agent Licence', 'Security', 'Licence', 'TAS', 'Security agent licence in Tasmania'),
  ('TAS Security Employee Registration', 'Security', 'Registration', 'TAS', 'Registration as a security employee in Tasmania'),
  ('TAS Commercial Passenger Vehicle Driver Accreditation', 'Transport', 'Accreditation', 'TAS', 'Accreditation to drive commercial passenger vehicles in Tasmania'),
  ('TAS Commercial Passenger Vehicle Service Licence', 'Transport', 'Licence', 'TAS', 'Licence to operate a commercial passenger vehicle service in Tasmania'),
  ('TAS Bus Driver Accreditation', 'Transport', 'Accreditation', 'TAS', 'Accreditation to drive buses in Tasmania'),
  ('TAS Liquor Licence (On-Premises)', 'Business', 'Licence', 'TAS', 'Licence to sell liquor for on-premises consumption in Tasmania'),
  ('TAS Liquor Licence (Off-Premises)', 'Business', 'Licence', 'TAS', 'Licence to sell packaged liquor in Tasmania'),
  ('TAS Liquor Licence (Club)', 'Business', 'Licence', 'TAS', 'Club liquor licence in Tasmania'),
  ('TAS Liquor Licence (Hotel)', 'Business', 'Licence', 'TAS', 'Hotel liquor licence in Tasmania'),
  ('TAS Liquor Licence (Restaurant)', 'Business', 'Licence', 'TAS', 'Restaurant liquor licence in Tasmania'),
  ('TAS General Liquor Licence', 'Business', 'Licence', 'TAS', 'General liquor licence in Tasmania'),
  ('TAS Gaming Machine Licence', 'Business', 'Licence', 'TAS', 'Licence to operate gaming machines in Tasmania'),
  ('TAS Bookmaker Licence', 'Business', 'Licence', 'TAS', 'Licence to operate as a bookmaker in Tasmania'),
  ('TAS Real Estate Agent Licence', 'Business', 'Licence', 'TAS', 'Licence to operate as a real estate agent in Tasmania'),
  ('TAS Motor Vehicle Trader Licence', 'Business', 'Licence', 'TAS', 'Licence to trade in motor vehicles in Tasmania'),
  ('TAS Motor Vehicle Repairer Registration', 'Business', 'Registration', 'TAS', 'Registration as a motor vehicle repairer in Tasmania'),
  ('TAS Second-Hand Dealer Licence', 'Business', 'Licence', 'TAS', 'Licence to deal in second-hand goods in Tasmania'),
  ('TAS Tattoo Parlour Licence', 'Business', 'Licence', 'TAS', 'Licence to operate a tattoo parlour in Tasmania'),
  ('TAS Skin Penetration Business Licence', 'Business', 'Licence', 'TAS', 'Licence for skin penetration businesses in Tasmania'),
  ('TAS Pawnbroker Licence', 'Business', 'Licence', 'TAS', 'Licence to operate as a pawnbroker in Tasmania'),
  ('TAS Food Business Registration', 'Hospitality', 'Registration', 'TAS', 'Registration of a food business in Tasmania'),
  ('ACT Builder Licence (Class A)', 'Construction', 'Licence', 'ACT', 'Class A builder licence for all building work in ACT'),
  ('ACT Builder Licence (Class B)', 'Construction', 'Licence', 'ACT', 'Class B builder licence for residential building work in ACT'),
  ('ACT Builder Licence (Class C)', 'Construction', 'Licence', 'ACT', 'Class C builder licence for construction work in ACT'),
  ('ACT Building Practitioner Registration', 'Construction', 'Registration', 'ACT', 'Registration as a building practitioner in ACT'),
  ('ACT Electrician Registration', 'Construction', 'Registration', 'ACT', 'Registration as an electrician in ACT'),
  ('ACT Plumber Registration', 'Construction', 'Registration', 'ACT', 'Registration as a plumber in ACT'),
  ('ACT Owner Builder Permit', 'Construction', 'Permit', 'ACT', 'Permit to act as owner builder in ACT'),
  ('ACT Security Agent Licence', 'Security', 'Licence', 'ACT', 'Security agent licence in ACT'),
  ('ACT Security Employee Registration', 'Security', 'Registration', 'ACT', 'Registration as a security employee in ACT'),
  ('ACT Commercial Passenger Vehicle Driver Accreditation', 'Transport', 'Accreditation', 'ACT', 'Accreditation to drive commercial passenger vehicles in ACT'),
  ('ACT Commercial Passenger Vehicle Service Licence', 'Transport', 'Licence', 'ACT', 'Licence to operate a commercial passenger vehicle service in ACT'),
  ('ACT Bus Driver Accreditation', 'Transport', 'Accreditation', 'ACT', 'Accreditation to drive buses in ACT'),
  ('ACT Liquor Licence (On-Premises)', 'Business', 'Licence', 'ACT', 'Licence to sell liquor for on-premises consumption in ACT'),
  ('ACT Liquor Licence (Off-Premises)', 'Business', 'Licence', 'ACT', 'Licence to sell packaged liquor in ACT'),
  ('ACT Liquor Licence (Club)', 'Business', 'Licence', 'ACT', 'Club liquor licence in ACT'),
  ('ACT Liquor Licence (Hotel)', 'Business', 'Licence', 'ACT', 'Hotel liquor licence in ACT'),
  ('ACT Liquor Licence (Restaurant)', 'Business', 'Licence', 'ACT', 'Restaurant liquor licence in ACT'),
  ('ACT General Liquor Licence', 'Business', 'Licence', 'ACT', 'General liquor licence in ACT'),
  ('ACT Gaming Machine Licence', 'Business', 'Licence', 'ACT', 'Licence to operate gaming machines in ACT'),
  ('ACT Bookmaker Licence', 'Business', 'Licence', 'ACT', 'Licence to operate as a bookmaker in ACT'),
  ('ACT Real Estate Agent Licence', 'Business', 'Licence', 'ACT', 'Licence to operate as a real estate agent in ACT'),
  ('ACT Motor Vehicle Dealer Licence', 'Business', 'Licence', 'ACT', 'Licence to operate as a motor vehicle dealer in ACT'),
  ('ACT Motor Vehicle Repairer Registration', 'Business', 'Registration', 'ACT', 'Registration as a motor vehicle repairer in ACT'),
  ('ACT Second-Hand Dealer Licence', 'Business', 'Licence', 'ACT', 'Licence to deal in second-hand goods in ACT'),
  ('ACT Tattoo Parlour Licence', 'Business', 'Licence', 'ACT', 'Licence to operate a tattoo parlour in ACT'),
  ('ACT Skin Penetration Business Licence', 'Business', 'Licence', 'ACT', 'Licence for skin penetration businesses in ACT'),
  ('ACT Pawnbroker Licence', 'Business', 'Licence', 'ACT', 'Licence to operate as a pawnbroker in ACT'),
  ('ACT Food Business Registration', 'Hospitality', 'Registration', 'ACT', 'Registration of a food business in ACT'),
  ('NT Builder Registration (Residential)', 'Construction', 'Registration', 'NT', 'Registration to build residential buildings in Northern Territory'),
  ('NT Builder Registration (Commercial)', 'Construction', 'Registration', 'NT', 'Registration to build commercial buildings in Northern Territory'),
  ('NT Building Practitioner Registration', 'Construction', 'Registration', 'NT', 'Registration as a building practitioner in Northern Territory'),
  ('NT Electrician Registration', 'Construction', 'Registration', 'NT', 'Registration as an electrician in Northern Territory'),
  ('NT Plumber Registration', 'Construction', 'Registration', 'NT', 'Registration as a plumber in Northern Territory'),
  ('NT Owner Builder Permit', 'Construction', 'Permit', 'NT', 'Permit to act as owner builder in Northern Territory'),
  ('NT Security Agent Licence', 'Security', 'Licence', 'NT', 'Security agent licence in Northern Territory'),
  ('NT Security Employee Registration', 'Security', 'Registration', 'NT', 'Registration as a security employee in Northern Territory'),
  ('NT Commercial Passenger Vehicle Driver Accreditation', 'Transport', 'Accreditation', 'NT', 'Accreditation to drive commercial passenger vehicles in Northern Territory'),
  ('NT Commercial Passenger Vehicle Service Licence', 'Transport', 'Licence', 'NT', 'Licence to operate a commercial passenger vehicle service in Northern Territory'),
  ('NT Bus Driver Accreditation', 'Transport', 'Accreditation', 'NT', 'Accreditation to drive buses in Northern Territory'),
  ('NT Liquor Licence (On-Premises)', 'Business', 'Licence', 'NT', 'Licence to sell liquor for on-premises consumption in Northern Territory'),
  ('NT Liquor Licence (Off-Premises)', 'Business', 'Licence', 'NT', 'Licence to sell packaged liquor in Northern Territory'),
  ('NT Liquor Licence (Club)', 'Business', 'Licence', 'NT', 'Club liquor licence in Northern Territory'),
  ('NT Liquor Licence (Hotel)', 'Business', 'Licence', 'NT', 'Hotel liquor licence in Northern Territory'),
  ('NT Liquor Licence (Restaurant)', 'Business', 'Licence', 'NT', 'Restaurant liquor licence in Northern Territory'),
  ('NT General Liquor Licence', 'Business', 'Licence', 'NT', 'General liquor licence in Northern Territory'),
  ('NT Gaming Machine Licence', 'Business', 'Licence', 'NT', 'Licence to operate gaming machines in Northern Territory'),
  ('NT Bookmaker Licence', 'Business', 'Licence', 'NT', 'Licence to operate as a bookmaker in Northern Territory'),
  ('NT Real Estate Agent Licence', 'Business', 'Licence', 'NT', 'Licence to operate as a real estate agent in Northern Territory'),
  ('NT Motor Vehicle Dealer Licence', 'Business', 'Licence', 'NT', 'Licence to operate as a motor vehicle dealer in Northern Territory'),
  ('NT Motor Vehicle Repairer Registration', 'Business', 'Registration', 'NT', 'Registration as a motor vehicle repairer in Northern Territory'),
  ('NT Second-Hand Dealer Licence', 'Business', 'Licence', 'NT', 'Licence to deal in second-hand goods in Northern Territory'),
  ('NT Tattoo Parlour Licence', 'Business', 'Licence', 'NT', 'Licence to operate a tattoo parlour in Northern Territory'),
  ('NT Skin Penetration Business Licence', 'Business', 'Licence', 'NT', 'Licence for skin penetration businesses in Northern Territory'),
  ('NT Pawnbroker Licence', 'Business', 'Licence', 'NT', 'Licence to operate as a pawnbroker in Northern Territory'),
  ('NT Food Business Registration', 'Hospitality', 'Registration', 'NT', 'Registration of a food business in Northern Territory'),
  ('Telecommunications Carrier Licence', 'IT', 'Licence', 'Federal', 'Licence to operate as a telecommunications carrier'),
  ('Telecommunications Service Provider Licence', 'IT', 'Licence', 'Federal', 'Licence to provide telecommunications services'),
  ('Radio Communications Licence', 'IT', 'Licence', 'Federal', 'Licence to operate radio communications equipment'),
  ('Amateur Radio Operator Licence', 'IT', 'Licence', 'Federal', 'Licence to operate amateur radio equipment'),
  ('Registered Professional Engineer of Queensland (RPEQ)', 'Engineering', 'Registration', 'QLD', 'Registration as a professional engineer in Queensland'),
  ('Certified Practising Project Director (CPPD)', 'Engineering', 'Certification', 'National', 'Certification as a practising project director'),
  ('Certified Practising Project Manager (CPPM)', 'Engineering', 'Certification', 'National', 'Certification as a practising project manager'),
  ('Specialist Medical Registration (Cardiology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in cardiology'),
  ('Specialist Medical Registration (Surgery)', 'Healthcare', 'Registration', 'National', 'Specialist registration in surgery'),
  ('Specialist Medical Registration (Paediatrics)', 'Healthcare', 'Registration', 'National', 'Specialist registration in paediatrics'),
  ('Specialist Medical Registration (Psychiatry)', 'Healthcare', 'Registration', 'National', 'Specialist registration in psychiatry'),
  ('Specialist Medical Registration (Anaesthesia)', 'Healthcare', 'Registration', 'National', 'Specialist registration in anaesthesia'),
  ('Specialist Medical Registration (Emergency Medicine)', 'Healthcare', 'Registration', 'National', 'Specialist registration in emergency medicine'),
  ('Specialist Medical Registration (General Practice)', 'Healthcare', 'Registration', 'National', 'Specialist registration in general practice'),
  ('Specialist Medical Registration (Obstetrics and Gynaecology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in obstetrics and gynaecology'),
  ('Specialist Medical Registration (Oncology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in oncology'),
  ('Specialist Medical Registration (Pathology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in pathology'),
  ('Specialist Medical Registration (Radiology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in radiology'),
  ('Specialist Medical Registration (Dermatology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in dermatology'),
  ('Specialist Medical Registration (Ophthalmology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in ophthalmology'),
  ('Specialist Medical Registration (Orthopaedic Surgery)', 'Healthcare', 'Registration', 'National', 'Specialist registration in orthopaedic surgery'),
  ('Specialist Medical Registration (Urology)', 'Healthcare', 'Registration', 'National', 'Specialist registration in urology'),
  ('Certificate IV in Training and Assessment (TAE40116)', 'Education', 'Certification', 'National', 'Certificate IV in Training and Assessment'),
  ('Diploma of Vocational Education and Training (TAE50116)', 'Education', 'Certification', 'National', 'Diploma of Vocational Education and Training'),
  ('Advanced Diploma of Vocational Education and Training (TAE60116)', 'Education', 'Certification', 'National', 'Advanced Diploma of Vocational Education and Training'),
  ('Certified Practising Builder (CPB)', 'Construction', 'Certification', 'National', 'Certification as a practising builder'),
  ('Registered Building Designer', 'Construction', 'Registration', 'National', 'Registration as a building designer'),
  ('Certified Building Designer', 'Construction', 'Certification', 'National', 'Certification as a building designer'),
  ('Fire Safety Assessor', 'Construction', 'Registration', 'National', 'Registration as a fire safety assessor'),
  ('Building Certifier Registration', 'Construction', 'Registration', 'National', 'Registration as a building certifier'),
  ('Energy Assessor Accreditation', 'Construction', 'Accreditation', 'National', 'Accreditation as an energy assessor'),
  ('Building Energy Efficiency Certificate Assessor', 'Construction', 'Certification', 'National', 'Certification as a building energy efficiency assessor'),
  ('Tax Agent Registration', 'Business', 'Registration', 'Federal', 'Registration as a tax agent with TPB'),
  ('BAS Agent Registration', 'Business', 'Registration', 'Federal', 'Registration as a BAS agent with TPB'),
  ('Tax (Financial) Adviser Registration', 'Business', 'Registration', 'Federal', 'Registration as a tax financial adviser with TPB'),
  ('Insolvency Practitioner Registration', 'Business', 'Registration', 'Federal', 'Registration as an insolvency practitioner'),
  ('Advanced Food Safety Supervisor', 'Hospitality', 'Certification', 'National', 'Advanced certification as a food safety supervisor'),
  ('Allergen Management Certification', 'Hospitality', 'Certification', 'National', 'Certification in allergen management for food service'),
  ('Food Safety Auditor', 'Hospitality', 'Certification', 'National', 'Certification as a food safety auditor'),
  ('Notary Public Appointment', 'Legal', 'Registration', 'National', 'Appointment as a notary public'),
  ('Conveyancer Registration', 'Legal', 'Registration', 'National', 'Registration as a conveyancer'),
  ('Licensed Conveyancer', 'Legal', 'Licence', 'National', 'Licence to practice as a conveyancer'),
  ('SMSF Auditor Registration', 'Finance', 'Registration', 'Federal', 'Registration as a self-managed superannuation fund auditor'),
  ('Tax Practitioner Registration', 'Finance', 'Registration', 'Federal', 'Registration as a tax practitioner'),
  ('Dangerous Goods Driver Licence', 'Transport', 'Licence', 'National', 'Licence to transport dangerous goods by road'),
  ('Forklift Operator Licence', 'Transport', 'Licence', 'National', 'Licence to operate forklifts (state-specific variations exist)'),
  ('Rail Industry Worker (RIW) Card', 'Transport', 'Card', 'National', 'Card required for railway workers'),
  ('Track Safety Awareness Card', 'Transport', 'Card', 'National', 'Card for railway track safety awareness'),
  ('Competency Card for Rail Infrastructure Workers', 'Transport', 'Card', 'National', 'Competency card for rail infrastructure work'),
  ('Security Systems Installer Licence', 'Security', 'Licence', 'National', 'Licence to install security systems'),
  ('Access Control System Installer Licence', 'Security', 'Licence', 'National', 'Licence to install access control systems'),
  ('CCTV System Installer Licence', 'Security', 'Licence', 'National', 'Licence to install CCTV systems'),
  ('Alarm Monitoring Centre Licence', 'Security', 'Licence', 'National', 'Licence to operate an alarm monitoring centre'),
  ('Speech Pathology Registration', 'Healthcare', 'Registration', 'National', 'Registration as a speech pathologist with AHPRA'),
  ('Audiology Registration', 'Healthcare', 'Registration', 'National', 'Registration as an audiologist'),
  ('Dietetics Registration', 'Healthcare', 'Registration', 'National', 'Registration as a dietitian with AHPRA'),
  ('Medical Laboratory Science Registration', 'Healthcare', 'Registration', 'National', 'Registration in medical laboratory science'),
  ('Social Work Registration', 'Healthcare', 'Registration', 'National', 'Registration as a social worker'),
  ('Counselling Registration', 'Healthcare', 'Registration', 'National', 'Registration as a counsellor (where applicable)'),
  ('Certified Practising Valuer (CPV)', 'Engineering', 'Certification', 'National', 'Certification as a practising valuer'),
  ('Registered Valuer', 'Engineering', 'Registration', 'National', 'Registration as a valuer'),
  ('Quantity Surveyor Registration', 'Engineering', 'Registration', 'National', 'Registration as a quantity surveyor'),
  ('Project Manager Registration', 'Engineering', 'Registration', 'National', 'Registration as a project manager'),
  ('Certified Practising Valuer (Property)', 'Engineering', 'Certification', 'National', 'Certification as a property valuer'),
  ('Microsoft Certified Solutions Expert (MCSE)', 'IT', 'Certification', 'National', 'Microsoft Certified Solutions Expert certification'),
  ('Cisco Certified Network Associate (CCNA)', 'IT', 'Certification', 'National', 'Cisco Certified Network Associate certification'),
  ('Certified Information Systems Security Professional (CISSP)', 'IT', 'Certification', 'National', 'CISSP certification for information security'),
  ('Amazon Web Services (AWS) Certified Solutions Architect', 'IT', 'Certification', 'National', 'AWS Certified Solutions Architect certification'),
  ('CompTIA Security+ Certification', 'IT', 'Certification', 'National', 'CompTIA Security+ certification'),
  ('Agricultural Pilot Licence', 'Agriculture', 'Licence', 'Federal', 'Licence to conduct aerial agricultural operations'),
  ('Veterinary Surgeon Registration (Specialist)', 'Agriculture', 'Registration', 'National', 'Specialist veterinary surgeon registration'),
  ('Animal Welfare Inspector Accreditation', 'Agriculture', 'Accreditation', 'National', 'Accreditation as an animal welfare inspector'),
  ('Biosecurity Officer Accreditation', 'Agriculture', 'Accreditation', 'Federal', 'Accreditation as a biosecurity officer'),
  ('NSW Gaming Machine Technician Licence', 'Business', 'Licence', 'NSW', 'Licence to service gaming machines in NSW'),
  ('NSW Massage Therapist Registration', 'Healthcare', 'Registration', 'NSW', 'Registration as a massage therapist in NSW'),
  ('NSW Pest Control Technician Licence', 'Business', 'Licence', 'NSW', 'Licence to provide pest control services in NSW'),
  ('NSW Building Certifier Accreditation', 'Construction', 'Accreditation', 'NSW', 'Accreditation as a building certifier in NSW'),
  ('NSW Energy Assessor Accreditation', 'Construction', 'Accreditation', 'NSW', 'Accreditation as an energy assessor in NSW'),
  ('VIC Building Surveyor Registration', 'Construction', 'Registration', 'VIC', 'Registration as a building surveyor in Victoria'),
  ('VIC Energy Assessor Registration', 'Construction', 'Registration', 'VIC', 'Registration as an energy assessor in Victoria'),
  ('VIC Building Inspector Registration', 'Construction', 'Registration', 'VIC', 'Registration as a building inspector in Victoria'),
  ('VIC Massage Therapist Registration', 'Healthcare', 'Registration', 'VIC', 'Registration as a massage therapist in Victoria'),
  ('VIC Pest Control Technician Licence', 'Business', 'Licence', 'VIC', 'Licence to provide pest control services in Victoria'),
  ('QLD Building Certifier Registration', 'Construction', 'Registration', 'QLD', 'Registration as a building certifier in Queensland'),
  ('QLD Energy Assessor Registration', 'Construction', 'Registration', 'QLD', 'Registration as an energy assessor in Queensland'),
  ('QLD Building Inspector Registration', 'Construction', 'Registration', 'QLD', 'Registration as a building inspector in Queensland'),
  ('QLD Massage Therapist Registration', 'Healthcare', 'Registration', 'QLD', 'Registration as a massage therapist in Queensland'),
  ('QLD Pest Control Technician Licence', 'Business', 'Licence', 'QLD', 'Licence to provide pest control services in Queensland'),
  ('SA Building Certifier Registration', 'Construction', 'Registration', 'SA', 'Registration as a building certifier in South Australia'),
  ('SA Energy Assessor Registration', 'Construction', 'Registration', 'SA', 'Registration as an energy assessor in South Australia'),
  ('SA Building Inspector Registration', 'Construction', 'Registration', 'SA', 'Registration as a building inspector in South Australia'),
  ('SA Massage Therapist Registration', 'Healthcare', 'Registration', 'SA', 'Registration as a massage therapist in South Australia'),
  ('SA Pest Control Technician Licence', 'Business', 'Licence', 'SA', 'Licence to provide pest control services in South Australia'),
  ('WA Building Surveyor Registration', 'Construction', 'Registration', 'WA', 'Registration as a building surveyor in Western Australia'),
  ('WA Energy Assessor Registration', 'Construction', 'Registration', 'WA', 'Registration as an energy assessor in Western Australia'),
  ('WA Building Inspector Registration', 'Construction', 'Registration', 'WA', 'Registration as a building inspector in Western Australia'),
  ('WA Massage Therapist Registration', 'Healthcare', 'Registration', 'WA', 'Registration as a massage therapist in Western Australia'),
  ('WA Pest Control Technician Licence', 'Business', 'Licence', 'WA', 'Licence to provide pest control services in Western Australia'),
  ('TAS Building Surveyor Registration', 'Construction', 'Registration', 'TAS', 'Registration as a building surveyor in Tasmania'),
  ('TAS Energy Assessor Registration', 'Construction', 'Registration', 'TAS', 'Registration as an energy assessor in Tasmania'),
  ('TAS Building Inspector Registration', 'Construction', 'Registration', 'TAS', 'Registration as a building inspector in Tasmania'),
  ('TAS Massage Therapist Registration', 'Healthcare', 'Registration', 'TAS', 'Registration as a massage therapist in Tasmania'),
  ('TAS Pest Control Technician Licence', 'Business', 'Licence', 'TAS', 'Licence to provide pest control services in Tasmania'),
  ('ACT Building Surveyor Registration', 'Construction', 'Registration', 'ACT', 'Registration as a building surveyor in ACT'),
  ('ACT Energy Assessor Registration', 'Construction', 'Registration', 'ACT', 'Registration as an energy assessor in ACT'),
  ('ACT Building Inspector Registration', 'Construction', 'Registration', 'ACT', 'Registration as a building inspector in ACT'),
  ('ACT Massage Therapist Registration', 'Healthcare', 'Registration', 'ACT', 'Registration as a massage therapist in ACT'),
  ('ACT Pest Control Technician Licence', 'Business', 'Licence', 'ACT', 'Licence to provide pest control services in ACT'),
  ('NT Building Surveyor Registration', 'Construction', 'Registration', 'NT', 'Registration as a building surveyor in Northern Territory'),
  ('NT Energy Assessor Registration', 'Construction', 'Registration', 'NT', 'Registration as an energy assessor in Northern Territory'),
  ('NT Building Inspector Registration', 'Construction', 'Registration', 'NT', 'Registration as a building inspector in Northern Territory'),
  ('NT Massage Therapist Registration', 'Healthcare', 'Registration', 'NT', 'Registration as a massage therapist in Northern Territory'),
  ('NT Pest Control Technician Licence', 'Business', 'Licence', 'NT', 'Licence to provide pest control services in Northern Territory'),
  ('Confined Space Entry Permit', 'Construction', 'Permit', 'National', 'Permit to work in confined spaces'),
  ('Working at Heights Certificate', 'Construction', 'Certification', 'National', 'Certification for working at heights safely'),
  ('Traffic Controller Certificate', 'Construction', 'Certification', 'National', 'Certification to control traffic in construction zones'),
  ('First Aid Certificate (HLTAID011)', 'Construction', 'Certification', 'National', 'Provide first aid certification'),
  ('CPR Certificate (HLTAID009)', 'Construction', 'Certification', 'National', 'Provide cardiopulmonary resuscitation certification'),
  ('Asbestos Awareness Training Certificate', 'Construction', 'Certification', 'National', 'Certificate in asbestos awareness training'),
  ('Excavator Operator Licence', 'Construction', 'Licence', 'National', 'Licence to operate excavators'),
  ('Bulldozer Operator Licence', 'Construction', 'Licence', 'National', 'Licence to operate bulldozers'),
  ('Loader Operator Licence', 'Construction', 'Licence', 'National', 'Licence to operate loaders'),
  ('Grader Operator Licence', 'Construction', 'Licence', 'National', 'Licence to operate graders'),
  ('Roller Operator Licence', 'Construction', 'Licence', 'National', 'Licence to operate rollers'),
  ('Bobcat Operator Licence', 'Construction', 'Licence', 'National', 'Licence to operate bobcats'),
  ('Mental Health First Aid Certificate', 'Healthcare', 'Certification', 'National', 'Certificate in mental health first aid'),
  ('Workplace First Aid Certificate', 'Healthcare', 'Certification', 'National', 'Workplace first aid certification'),
  ('Advanced Life Support Certificate', 'Healthcare', 'Certification', 'National', 'Advanced life support certification for healthcare providers'),
  ('Paediatric Life Support Certificate', 'Healthcare', 'Certification', 'National', 'Paediatric life support certification'),
  ('Neonatal Resuscitation Certificate', 'Healthcare', 'Certification', 'National', 'Neonatal resuscitation certification'),
  ('Infection Prevention and Control Certificate', 'Healthcare', 'Certification', 'National', 'Certificate in infection prevention and control'),
  ('Medication Administration Certificate', 'Healthcare', 'Certification', 'National', 'Certificate for medication administration'),
  ('Wound Care Certificate', 'Healthcare', 'Certification', 'National', 'Certificate in wound care management'),
  ('Dementia Care Certificate', 'Healthcare', 'Certification', 'National', 'Certificate in dementia care'),
  ('Palliative Care Certificate', 'Healthcare', 'Certification', 'National', 'Certificate in palliative care'),
  ('Certificate III in Education Support (CHC30221)', 'Education', 'Certification', 'National', 'Certificate III in education support'),
  ('Certificate IV in Education Support (CHC40221)', 'Education', 'Certification', 'National', 'Certificate IV in education support'),
  ('Diploma of Early Childhood Education and Care (CHC50121)', 'Education', 'Certification', 'National', 'Diploma of early childhood education and care'),
  ('Certificate III in Early Childhood Education and Care (CHC30121)', 'Education', 'Certification', 'National', 'Certificate III in early childhood education and care'),
  ('Working with Children Check', 'Education', 'Clearance', 'National', 'National clearance to work with children (varies by state)'),
  ('Close Personal Protection Licence', 'Security', 'Licence', 'National', 'Licence for close personal protection services'),
  ('Security Control Room Operator Licence', 'Security', 'Licence', 'National', 'Licence to operate security control rooms'),
  ('Cash-in-Transit Operator Licence', 'Security', 'Licence', 'National', 'Licence to operate cash-in-transit services'),
  ('Armoured Vehicle Operator Licence', 'Security', 'Licence', 'National', 'Licence to operate armoured vehicles'),
  ('Security Dog Handler Licence', 'Security', 'Licence', 'National', 'Licence to handle security dogs'),
  ('Crowd Controller Supervisor Licence', 'Security', 'Licence', 'National', 'Supervisor licence for crowd control operations'),
  ('CompTIA A+ Certification', 'IT', 'Certification', 'National', 'CompTIA A+ certification for IT support'),
  ('CompTIA Network+ Certification', 'IT', 'Certification', 'National', 'CompTIA Network+ certification'),
  ('Microsoft Azure Administrator Certification', 'IT', 'Certification', 'National', 'Microsoft Azure Administrator Associate certification'),
  ('Google Cloud Professional Cloud Architect Certification', 'IT', 'Certification', 'National', 'Google Cloud Professional Cloud Architect certification'),
  ('AWS Certified Cloud Practitioner Certification', 'IT', 'Certification', 'National', 'AWS Certified Cloud Practitioner certification'),
  ('Certified Ethical Hacker (CEH) Certification', 'IT', 'Certification', 'National', 'Certified Ethical Hacker certification'),
  ('Certified Information Security Manager (CISM) Certification', 'IT', 'Certification', 'National', 'CISM certification for information security management'),
  ('Certified Information Systems Auditor (CISA) Certification', 'IT', 'Certification', 'National', 'CISA certification for information systems auditing'),
  ('ITIL Foundation Certification', 'IT', 'Certification', 'National', 'ITIL Foundation certification for IT service management'),
  ('PRINCE2 Foundation Certification', 'IT', 'Certification', 'National', 'PRINCE2 Foundation certification for project management'),
  ('Agile Scrum Master Certification', 'IT', 'Certification', 'National', 'Agile Scrum Master certification'),
  ('PMP Certification (Project Management Professional)', 'IT', 'Certification', 'National', 'Project Management Professional certification from PMI'),
  ('Certified Practising Valuer (CPV) - Property', 'Engineering', 'Certification', 'National', 'Certification as a property valuer'),
  ('Registered Property Valuer', 'Engineering', 'Registration', 'National', 'Registration as a property valuer'),
  ('Quantity Surveyor Certification', 'Engineering', 'Certification', 'National', 'Certification as a quantity surveyor'),
  ('Building Estimator Certification', 'Engineering', 'Certification', 'National', 'Certification as a building estimator'),
  ('Construction Project Manager Certification', 'Engineering', 'Certification', 'National', 'Certification as a construction project manager'),
  ('Civil Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as a civil engineer'),
  ('Structural Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as a structural engineer'),
  ('Mechanical Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as a mechanical engineer'),
  ('Electrical Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as an electrical engineer'),
  ('Chemical Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as a chemical engineer'),
  ('Environmental Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as an environmental engineer'),
  ('Mining Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as a mining engineer'),
  ('Aerospace Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as an aerospace engineer'),
  ('Biomedical Engineer Registration', 'Engineering', 'Registration', 'National', 'Registration as a biomedical engineer'),
  ('Financial Planner Registration', 'Finance', 'Registration', 'Federal', 'Registration as a financial planner with ASIC'),
  ('Credit Representative Registration', 'Finance', 'Registration', 'Federal', 'Registration as a credit representative'),
  ('Mortgage Broker Registration', 'Finance', 'Registration', 'Federal', 'Registration as a mortgage broker'),
  ('Insurance Broker Registration', 'Finance', 'Registration', 'Federal', 'Registration as an insurance broker'),
  ('Loss Adjuster Registration', 'Finance', 'Registration', 'Federal', 'Registration as a loss adjuster'),
  ('Actuary Registration', 'Finance', 'Registration', 'National', 'Registration as an actuary'),
  ('Pesticide Applicator Licence', 'Agriculture', 'Licence', 'National', 'Licence to apply pesticides'),
  ('Veterinary Nurse Registration', 'Agriculture', 'Registration', 'National', 'Registration as a veterinary nurse'),
  ('Animal Handler Certification', 'Agriculture', 'Certification', 'National', 'Certification for animal handling'),
  ('Livestock Transport Accreditation', 'Agriculture', 'Accreditation', 'National', 'Accreditation for livestock transport'),
  ('RSA Online Certificate', 'Hospitality', 'Certification', 'National', 'Responsible Service of Alcohol online certification'),
  ('RCG Online Certificate', 'Hospitality', 'Certification', 'National', 'Responsible Conduct of Gambling online certification'),
  ('Advanced Food Safety Supervisor Certificate', 'Hospitality', 'Certification', 'National', 'Advanced certification as a food safety supervisor'),
  ('Food Safety Auditor Certification', 'Hospitality', 'Certification', 'National', 'Certification as a food safety auditor'),
  ('Barista Certification', 'Hospitality', 'Certification', 'National', 'Certification as a barista'),
  ('Sommelier Certification', 'Hospitality', 'Certification', 'National', 'Certification as a sommelier'),
  ('Chef Certification', 'Hospitality', 'Certification', 'National', 'Certification as a professional chef'),
  ('Gaming Machine Technician Licence', 'Hospitality', 'Licence', 'National', 'Licence to service gaming machines'),
  ('Mediator Accreditation', 'Legal', 'Accreditation', 'National', 'Accreditation as a mediator'),
  ('Arbitrator Accreditation', 'Legal', 'Accreditation', 'National', 'Accreditation as an arbitrator'),
  ('Family Dispute Resolution Practitioner Registration', 'Legal', 'Registration', 'National', 'Registration as a family dispute resolution practitioner'),
  ('Will Writer Registration', 'Legal', 'Registration', 'National', 'Registration as a will writer'),
  ('Passenger Transport Driver Authority', 'Transport', 'Licence', 'National', 'Authority to drive passenger transport vehicles (state-specific)'),
  ('Commercial Vehicle Operator Registration', 'Transport', 'Registration', 'National', 'Registration as a commercial vehicle operator'),
  ('NSW Working with Children Check', 'Education', 'Clearance', 'NSW', 'NSW clearance to work with children'),
  ('NSW First Aid Certificate', 'Healthcare', 'Certification', 'NSW', 'First aid certificate valid in NSW'),
  ('NSW Traffic Controller Certificate', 'Construction', 'Certification', 'NSW', 'Certificate to control traffic in NSW'),
  ('NSW Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'NSW', 'Licence to remove friable asbestos in NSW'),
  ('NSW Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'NSW', 'Licence to remove non-friable asbestos in NSW'),
  ('NSW Demolition Licence', 'Construction', 'Licence', 'NSW', 'Licence to perform demolition work in NSW'),
  ('NSW Explosives Licence', 'Construction', 'Licence', 'NSW', 'Licence to handle explosives in NSW'),
  ('NSW Pyrotechnician Licence', 'Business', 'Licence', 'NSW', 'Licence to conduct pyrotechnic displays in NSW'),
  ('VIC Working with Children Check', 'Education', 'Clearance', 'VIC', 'Victoria clearance to work with children'),
  ('VIC First Aid Certificate', 'Healthcare', 'Certification', 'VIC', 'First aid certificate valid in Victoria'),
  ('VIC Traffic Controller Certificate', 'Construction', 'Certification', 'VIC', 'Certificate to control traffic in Victoria'),
  ('VIC Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'VIC', 'Licence to remove friable asbestos in Victoria'),
  ('VIC Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'VIC', 'Licence to remove non-friable asbestos in Victoria'),
  ('VIC Demolition Licence', 'Construction', 'Licence', 'VIC', 'Licence to perform demolition work in Victoria'),
  ('VIC Explosives Licence', 'Construction', 'Licence', 'VIC', 'Licence to handle explosives in Victoria'),
  ('VIC Pyrotechnician Licence', 'Business', 'Licence', 'VIC', 'Licence to conduct pyrotechnic displays in Victoria'),
  ('QLD Working with Children Check (Blue Card)', 'Education', 'Clearance', 'QLD', 'Queensland Blue Card to work with children'),
  ('QLD First Aid Certificate', 'Healthcare', 'Certification', 'QLD', 'First aid certificate valid in Queensland'),
  ('QLD Traffic Controller Certificate', 'Construction', 'Certification', 'QLD', 'Certificate to control traffic in Queensland'),
  ('QLD Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'QLD', 'Licence to remove friable asbestos in Queensland'),
  ('QLD Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'QLD', 'Licence to remove non-friable asbestos in Queensland'),
  ('QLD Demolition Licence', 'Construction', 'Licence', 'QLD', 'Licence to perform demolition work in Queensland'),
  ('QLD Explosives Licence', 'Construction', 'Licence', 'QLD', 'Licence to handle explosives in Queensland'),
  ('QLD Pyrotechnician Licence', 'Business', 'Licence', 'QLD', 'Licence to conduct pyrotechnic displays in Queensland'),
  ('SA Working with Children Check', 'Education', 'Clearance', 'SA', 'South Australia clearance to work with children'),
  ('SA First Aid Certificate', 'Healthcare', 'Certification', 'SA', 'First aid certificate valid in South Australia'),
  ('SA Traffic Controller Certificate', 'Construction', 'Certification', 'SA', 'Certificate to control traffic in South Australia'),
  ('SA Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'SA', 'Licence to remove friable asbestos in South Australia'),
  ('SA Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'SA', 'Licence to remove non-friable asbestos in South Australia'),
  ('SA Demolition Licence', 'Construction', 'Licence', 'SA', 'Licence to perform demolition work in South Australia'),
  ('SA Explosives Licence', 'Construction', 'Licence', 'SA', 'Licence to handle explosives in South Australia'),
  ('SA Pyrotechnician Licence', 'Business', 'Licence', 'SA', 'Licence to conduct pyrotechnic displays in South Australia'),
  ('WA Working with Children Check', 'Education', 'Clearance', 'WA', 'Western Australia clearance to work with children'),
  ('WA First Aid Certificate', 'Healthcare', 'Certification', 'WA', 'First aid certificate valid in Western Australia'),
  ('WA Traffic Controller Certificate', 'Construction', 'Certification', 'WA', 'Certificate to control traffic in Western Australia'),
  ('WA Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'WA', 'Licence to remove friable asbestos in Western Australia'),
  ('WA Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'WA', 'Licence to remove non-friable asbestos in Western Australia'),
  ('WA Demolition Licence', 'Construction', 'Licence', 'WA', 'Licence to perform demolition work in Western Australia'),
  ('WA Explosives Licence', 'Construction', 'Licence', 'WA', 'Licence to handle explosives in Western Australia'),
  ('WA Pyrotechnician Licence', 'Business', 'Licence', 'WA', 'Licence to conduct pyrotechnic displays in Western Australia'),
  ('TAS Working with Children Registration', 'Education', 'Registration', 'TAS', 'Tasmania registration to work with children'),
  ('TAS First Aid Certificate', 'Healthcare', 'Certification', 'TAS', 'First aid certificate valid in Tasmania'),
  ('TAS Traffic Controller Certificate', 'Construction', 'Certification', 'TAS', 'Certificate to control traffic in Tasmania'),
  ('TAS Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'TAS', 'Licence to remove friable asbestos in Tasmania'),
  ('TAS Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'TAS', 'Licence to remove non-friable asbestos in Tasmania'),
  ('TAS Demolition Licence', 'Construction', 'Licence', 'TAS', 'Licence to perform demolition work in Tasmania'),
  ('TAS Explosives Licence', 'Construction', 'Licence', 'TAS', 'Licence to handle explosives in Tasmania'),
  ('TAS Pyrotechnician Licence', 'Business', 'Licence', 'TAS', 'Licence to conduct pyrotechnic displays in Tasmania'),
  ('ACT Working with Vulnerable People Registration', 'Education', 'Registration', 'ACT', 'ACT registration to work with vulnerable people'),
  ('ACT First Aid Certificate', 'Healthcare', 'Certification', 'ACT', 'First aid certificate valid in ACT'),
  ('ACT Traffic Controller Certificate', 'Construction', 'Certification', 'ACT', 'Certificate to control traffic in ACT'),
  ('ACT Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'ACT', 'Licence to remove friable asbestos in ACT'),
  ('ACT Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'ACT', 'Licence to remove non-friable asbestos in ACT'),
  ('ACT Demolition Licence', 'Construction', 'Licence', 'ACT', 'Licence to perform demolition work in ACT'),
  ('ACT Explosives Licence', 'Construction', 'Licence', 'ACT', 'Licence to handle explosives in ACT'),
  ('ACT Pyrotechnician Licence', 'Business', 'Licence', 'ACT', 'Licence to conduct pyrotechnic displays in ACT'),
  ('NT Working with Children Clearance (Ochre Card)', 'Education', 'Clearance', 'NT', 'Northern Territory Ochre Card to work with children'),
  ('NT First Aid Certificate', 'Healthcare', 'Certification', 'NT', 'First aid certificate valid in Northern Territory'),
  ('NT Traffic Controller Certificate', 'Construction', 'Certification', 'NT', 'Certificate to control traffic in Northern Territory'),
  ('NT Asbestos Removal Licence (Class A)', 'Construction', 'Licence', 'NT', 'Licence to remove friable asbestos in Northern Territory'),
  ('NT Asbestos Removal Licence (Class B)', 'Construction', 'Licence', 'NT', 'Licence to remove non-friable asbestos in Northern Territory'),
  ('NT Demolition Licence', 'Construction', 'Licence', 'NT', 'Licence to perform demolition work in Northern Territory'),
  ('NT Explosives Licence', 'Construction', 'Licence', 'NT', 'Licence to handle explosives in Northern Territory'),
  ('NT Pyrotechnician Licence', 'Business', 'Licence', 'NT', 'Licence to conduct pyrotechnic displays in Northern Territory');
