-- Creerlio: Business Bank (documents, images, video) - additive
-- Business-side equivalent of Talent Bank: private upload library + metadata rows.

create table if not exists public.business_bank_items (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.business_profiles(id) on delete cascade,
  user_id uuid not null,
  item_type text not null check (item_type in ('document','image','video')),
  title text not null,
  description text,
  file_path text,
  file_type text,
  file_size bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists business_bank_items_business_id_idx on public.business_bank_items(business_id);
create index if not exists business_bank_items_user_id_idx on public.business_bank_items(user_id);
create index if not exists business_bank_items_created_at_idx on public.business_bank_items(created_at desc);

alter table public.business_bank_items enable row level security;

-- Business owners can manage their own Business Bank items.
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname='public' and tablename='business_bank_items' and policyname='business_owner_manage_business_bank'
  ) then
    create policy business_owner_manage_business_bank
      on public.business_bank_items
      for all
      to authenticated
      using (
        exists (
          select 1
          from public.business_profiles bp
          where bp.id = business_bank_items.business_id
            and bp.user_id = auth.uid()
        )
      )
      with check (
        exists (
          select 1
          from public.business_profiles bp
          where bp.id = business_bank_items.business_id
            and bp.user_id = auth.uid()
        )
      );
  end if;
end $$;

-- Storage bucket: private (signed URLs only)
insert into storage.buckets (id, name, public)
values ('business-bank', 'business-bank', false)
on conflict (id) do nothing;

-- Storage policies for business-bank:
-- Required object path format:
--   business/<business_id>/<filename>
do $$
begin
  -- Owner read (authenticated)
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'business_owner_read_business_bank'
  ) then
    create policy business_owner_read_business_bank
      on storage.objects
      for select
      to authenticated
      using (
        bucket_id = 'business-bank'
        and split_part(name, '/', 1) = 'business'
        and (split_part(name, '/', 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
        and exists (
          select 1
          from public.business_profiles bp
          where bp.id = (split_part(name, '/', 2))::uuid
            and bp.user_id = auth.uid()
        )
      );
  end if;

  -- Owner insert
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'business_owner_insert_business_bank'
  ) then
    create policy business_owner_insert_business_bank
      on storage.objects
      for insert
      to authenticated
      with check (
        bucket_id = 'business-bank'
        and split_part(name, '/', 1) = 'business'
        and (split_part(name, '/', 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
        and exists (
          select 1
          from public.business_profiles bp
          where bp.id = (split_part(name, '/', 2))::uuid
            and bp.user_id = auth.uid()
        )
      );
  end if;

  -- Owner update
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'business_owner_update_business_bank'
  ) then
    create policy business_owner_update_business_bank
      on storage.objects
      for update
      to authenticated
      using (
        bucket_id = 'business-bank'
        and split_part(name, '/', 1) = 'business'
        and (split_part(name, '/', 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
        and exists (
          select 1
          from public.business_profiles bp
          where bp.id = (split_part(name, '/', 2))::uuid
            and bp.user_id = auth.uid()
        )
      )
      with check (
        bucket_id = 'business-bank'
        and split_part(name, '/', 1) = 'business'
        and (split_part(name, '/', 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
        and exists (
          select 1
          from public.business_profiles bp
          where bp.id = (split_part(name, '/', 2))::uuid
            and bp.user_id = auth.uid()
        )
      );
  end if;

  -- Owner delete
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'business_owner_delete_business_bank'
  ) then
    create policy business_owner_delete_business_bank
      on storage.objects
      for delete
      to authenticated
      using (
        bucket_id = 'business-bank'
        and split_part(name, '/', 1) = 'business'
        and (split_part(name, '/', 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
        and exists (
          select 1
          from public.business_profiles bp
          where bp.id = (split_part(name, '/', 2))::uuid
            and bp.user_id = auth.uid()
        )
      );
  end if;
end $$;


